### ISSUE TITLE
Ability to cancel request execution

### ISSUE THREAD

**Issue by wonderfly** [google/google-http-java-client#172] opened 2015-01-09 23:20 UTC
_From [yan...@google.com](https://code.google.com/u/111815493751521097215/) on December 03, 2012 08:06:10_

External references, such as a standards document, or specification? http://javadoc.google-http-java-client.googlecode.com/hg/1.12.0-beta/com/google/api/client/http/HttpRequest.html https://code.google.com/p/google-http-java-client/issues/detail?id=2 https://code.google.com/p/google-api-java-client/issues/detail?id=671 Java environments (e.g. Java 6, Android 2.3, App Engine, or All)? All Please describe the feature requested. If an application has a cancel button, it may want to abort the current operation.  If the current operation is an HTTP request execute, it may be expensive to wait for it to complete.  Once possible way to accomplish this is to simply shut down the thread in which the HTTP request is running.  That may be a bit too rough for some applications, and may not fit the threading model of some use cases, such as with AsyncTask example linked above.  Instead one may wish to do a soft cancellation, in which some isCanceled flag is checked frequently whenever it is convenient to do so.

Note that HttpRequest is currently not designed for being called from a second thread.  So such a change would be a fairly significant one from a design point of view.

_Original issue: http://code.google.com/p/google-http-java-client/issues/detail?id=172_

**Comment by mattwhisenhunt** [comment] 2018-01-08 19:49
Duplicate of #343

**Closed by mattwhisenhunt** 2018-01-08 19:49 UTC
Labels: 2–5 stars, Component-HTTP, imported, priority: p2, type: feature request
