### ISSUE TITLE
unexpected end of stream on com.android.okhttp.Address

### ISSUE THREAD

**Issue by connect2satz** [google/google-http-java-client#399] opened 2018-03-14 08:44 UTC
Getting this exception sometime.

IO Exception [0] http request failed: [class java.io.IOException] unexpected end of stream on com.android.okhttp.Address@d8f9801b
03-14 14:13:59.338 : java.io.IOException: unexpected end of stream on com.android.okhttp.Address@d8f9801b
03-14 14:13:59.338 : 	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:201)
03-14 14:13:59.338 : 	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
03-14 14:13:59.338 : 	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
03-14 14:13:59.338 : 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
03-14 14:13:59.338 : 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
03-14 14:13:59.338 : 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
03-14 14:13:59.338 : 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
03-14 14:13:59.338 : 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
03-14 14:13:59.338 : 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(Unknown Source:0)
03-14 14:13:59.338 : 	at com.google.api.client.http.javanet.NetHttpResponse.<init>(NetHttpResponse.java:37)
03-14 14:13:59.338 : 	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:105)
03-14 14:13:59.338 : 	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
03-14 14:13:59.338 : 	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:200)
03-14 14:13:59.338 : 	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
03-14 14:13:59.662 : IO Exception [1] http request failed: [class java.net.ConnectException] Failed to connect to <ServerIp>:443
03-14 14:13:59.681 : 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
03-14 14:13:59.681 : 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
03-14 14:13:59.681 : 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
03-14 14:13:59.681 : 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
03-14 14:13:59.681 : 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
03-14 14:13:59.681 : 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
03-14 14:13:59.681 : 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
03-14 14:13:59.681 : 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
03-14 14:13:59.681 : 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
03-14 14:13:59.681 : 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
03-14 14:13:59.681 : 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
03-14 14:13:59.681 : 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(Unknown Source:0)
03-14 14:13:59.681 : 	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
03-14 14:13:59.681 : 	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
03-14 14:13:59.692 : 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
03-14 14:13:59.692 : 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
03-14 14:13:59.692 : 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
03-14 14:13:59.692 : 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
03-14 14:13:59.692 : 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
03-14 14:13:59.692 : 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
03-14 14:13:59.692 : 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
03-14 14:13:59.692 : 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
03-14 14:13:59.692 : 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
03-14 14:13:59.692 : 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
03-14 14:13:59.692 : 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
03-14 14:13:59.692 : 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(Unknown Source:0)
03-14 14:13:59.692 : 	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
03-14 14:13:59.692 : 	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)

**Comment by mattwhisenhunt** [comment] 2018-03-15 20:25
Duplicate of #397

**Closed by mattwhisenhunt** 2018-03-15 20:25 UTC
Labels: type: question

**Comment by iFarSeer** [comment] 2019-06-28 02:47
> Getting this exception sometime.
> 
> IO Exception [0] http request failed: [class java.io.IOException] unexpected end of stream on com.android.okhttp.Address@d8f9801b
> 03-14 14:13:59.338 : java.io.IOException: unexpected end of stream on com.android.okhttp.Address@d8f9801b
> 03-14 14:13:59.338 : at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:201)
> 03-14 14:13:59.338 : at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
> 03-14 14:13:59.338 : at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
> 03-14 14:13:59.338 : at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
> 03-14 14:13:59.338 : at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
> 03-14 14:13:59.338 : at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
> 03-14 14:13:59.338 : at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
> 03-14 14:13:59.338 : at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
> 03-14 14:13:59.338 : at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(Unknown Source:0)
> 03-14 14:13:59.338 : at com.google.api.client.http.javanet.NetHttpResponse.(NetHttpResponse.java:37)
> 03-14 14:13:59.338 : at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:105)
> 03-14 14:13:59.338 : at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
> 03-14 14:13:59.338 : at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:200)
> 03-14 14:13:59.338 : at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
> 03-14 14:13:59.662 : IO Exception [1] http request failed: [class java.net.ConnectException] Failed to connect to :443
> 03-14 14:13:59.681 : at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
> 03-14 14:13:59.681 : at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
> 03-14 14:13:59.681 : at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
> 03-14 14:13:59.681 : at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
> 03-14 14:13:59.681 : at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
> 03-14 14:13:59.681 : at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
> 03-14 14:13:59.681 : at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
> 03-14 14:13:59.681 : at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
> 03-14 14:13:59.681 : at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
> 03-14 14:13:59.681 : at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
> 03-14 14:13:59.681 : at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
> 03-14 14:13:59.681 : at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(Unknown Source:0)
> 03-14 14:13:59.681 : at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
> 03-14 14:13:59.681 : at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
> 03-14 14:13:59.692 : at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
> 03-14 14:13:59.692 : at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
> 03-14 14:13:59.692 : at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
> 03-14 14:13:59.692 : at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
> 03-14 14:13:59.692 : at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
> 03-14 14:13:59.692 : at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
> 03-14 14:13:59.692 : at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
> 03-14 14:13:59.692 : at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
> 03-14 14:13:59.692 : at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
> 03-14 14:13:59.692 : at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
> 03-14 14:13:59.692 : at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
> 03-14 14:13:59.692 : at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(Unknown Source:0)
> 03-14 14:13:59.692 : at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
> 03-14 14:13:59.692 : at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)

Have you fixed this problem?
